### ISSUE TITLE
Halloween Stick drops way too much

### ISSUE THREAD

**Issue by riskable** [Corail31/the_flying_things_support#1]
Minor gripe: I've set `chance_drop_pumpkin_stick` to 5 and I still get those Halloween Sticks _constantly_.  I don't think your code is calculating the percentage correctly or something.  I just set it to 0 but it would be nice if it actually *was* a super rare drop/loot item.

Cool mod BTW.  It's super fun to take the carpet down to earth and just break loads of grass and flowers =)

**Comment by Corail31** [comment]
Hi Riskable, you're right, the chance should be on 1000 to be rarer :) (it's 5 on 100 so 20% to get a stick on agressive entity)
NB : sticks also appear because the config option "persistantHolidays" is enabled.

**Comment by riskable** [comment]
OK, so higher numbers are rarer?  Strange.  That's the opposite of what seems logical but that's fine...  Maybe make a note about that in the default comments in the file?  Anyway, thanks for taking the time to investigate!

**Comment by Corail31** [comment]
@riskable i'm not english native meaning what i write may be understood differently, but i just say you actually the config is set to be on 1000 but the code handles it like if it was on 100 and i'll publish the fix in a few minutes ;)
